name: Deploy go files

on:
  push:
    branches:
      - main # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/"
          target: "/root/web/pepsi"
